# Feature Selection Embedded

In [60]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_curve, auc, confusion_matrix, classification_report,accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
%matplotlib inline

### Cible 'Died'

#### Ridge

In [111]:
data = pd.read_csv("DataM.csv")
names=['litt_size','TPI','Diarr','hospit','InfCroissPed', 'InfCroiss4', 'InfCroiss5', 'InfCroiss6', 'InfCroiss7', 'InfCroiss8', 'TRD21', 'TRD22', 'TRD23', 'TRD24', 'TRD25', 'TRD26', 'TRD27', 'TRD28', 'TRD29', 'TRD30', 'TRD31', 'TRD32', 'TRD33', 'TRD34', 'TRD35', 'TRD36', 'TRD37', 'TRD38', 'TRD39', 'TRD40', 'TRD41', 'TRD42', 'TRD43', 'TRD21', 'TRD44', 'TRD45', 'TRD46', 'TRD47', 'TRD48', 'TRD49', 'TRD50', 'TRD51', 'TRD52', 'TRD53', 'TRD54', 'TRD55', 'TRD56']
data.fillna(0, inplace=True)
del data['ID']
del data['ID_litter']
del data['group']
del data['IgGJ2']
del data['AgeD2']
del data['Age_D1']
del data['Min1inflcr']
del data['Size']
del data['sex']
data.head()

,litt_size,TPI,Diarr,hospit,InfCroissPed,InfCroiss4,InfCroiss5,InfCroiss6,InfCroiss7,InfCroiss8,...,TRD48,TRD49,TRD50,TRD51,TRD52,TRD53,TRD54,TRD55,TRD56,Died
0,5,0.0,1,1,1,1,0,0,0.0,0.0,...,38.4,38.2,38.4,38.9,38.7,38.5,38.7,39.0,39.0,1
1,5,0.0,1,0,1,1,0,0,0.0,0.0,...,38.4,37.4,37.8,39.1,38.1,38.7,37.7,37.9,38.3,0
2,5,0.0,0,0,1,0,1,0,0.0,0.0,...,38.2,38.4,38.1,38.8,39.1,37.4,38.0,38.2,37.6,0
3,5,0.0,1,1,1,0,1,0,0.0,0.0,...,38.4,38.4,38.4,38.9,38.3,38.5,38.6,38.0,38.0,0
4,5,0.0,1,1,1,0,1,0,0.0,1.0,...,38.3,38.7,38.6,39.1,37.4,37.4,37.4,37.4,37.4,0

In [112]:
from sklearn.linear_model import Ridge
X=data.drop(["Died"], axis = 1)
Y=data['Died']
ridge = Ridge(alpha=1.0)
ridge.fit(X,Y)

Ridge()

In [113]:
ridge=Ridge(alpha=1.0)
ridge.fit(X,Y)
predictors=X.columns
coef=pd.Series(ridge.coef_,predictors).sort_values(ascending=False)
print(coef)

TRD45           0.269147
hospit          0.185809
Diarr           0.163864
TRD50           0.153662
TRD35           0.135219
TRD37           0.133265
TRD25           0.120417
TRD54           0.113093
TRD23           0.086972
TRD40           0.078591
InfCroiss7      0.038270
TRD56           0.037458
TRD33           0.032804
TRD24           0.027442
TRD51           0.025563
TRD46           0.013522
TRD26           0.011774
TRD52           0.011265
InfCroissPed    0.005550
TRD30          -0.001350
TRD47          -0.008726
TRD55          -0.008887
TRD38          -0.010862
InfCroiss6     -0.013439
TRD42          -0.014095
litt_size      -0.014282
TRD41          -0.016553
TRD29          -0.022343
TRD27          -0.024457
TRD39          -0.026444
TRD49          -0.027876
TRD48          -0.028505
InfCroiss4     -0.032319
TRD22          -0.033864
TRD31          -0.036744
TRD34          -0.041428
TRD43          -0.050800
TRD32          -0.055455
TPI            -0.058678
TRD28          -0.069739
TRD21          -0.077155
TRD53          -0.131913
TRD44          -0.133631
InfCroiss8     -0.152793
TRD36          -0.154794
InfCroiss5     -0.184683
dtype: float64

#### Lasso

In [107]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=1)
lasso.fit(X,Y)
predictors=X.columns
coef=pd.Series(lasso.coef_,predictors).sort_values()
print(coef)

litt_size       0.0
TRD36          -0.0
TRD37           0.0
TRD38           0.0
TRD39           0.0
TRD40           0.0
TRD41          -0.0
TRD42           0.0
TRD43           0.0
TRD44          -0.0
TRD45           0.0
TRD46           0.0
TRD47           0.0
TRD48           0.0
TRD49           0.0
TRD50           0.0
TRD51           0.0
TRD52           0.0
TRD53          -0.0
TRD54           0.0
TRD35           0.0
TRD34           0.0
TRD33           0.0
TRD32           0.0
TPI            -0.0
Diarr           0.0
hospit          0.0
InfCroissPed    0.0
InfCroiss4     -0.0
InfCroiss5     -0.0
InfCroiss6      0.0
InfCroiss7      0.0
InfCroiss8     -0.0
TRD55           0.0
TRD21          -0.0
TRD23           0.0
TRD24           0.0
TRD25           0.0
TRD26           0.0
TRD27          -0.0
TRD28          -0.0
TRD29          -0.0
TRD30           0.0
TRD31           0.0
TRD22           0.0
TRD56           0.0
dtype: float64

### Cible 'Diarr'

#### Ridge

In [98]:
data = pd.read_csv("DataD.csv")
names=['litt_size','TPI','Diarr','hospit','InfCroissPed', 'InfCroiss4', 'InfCroiss5', 'InfCroiss6', 'InfCroiss7', 'InfCroiss8', 'TRD21', 'TRD22', 'TRD23', 'TRD24', 'TRD25', 'TRD26', 'TRD27', 'TRD28', 'TRD29', 'TRD30', 'TRD31', 'TRD32', 'TRD33', 'TRD34', 'TRD35', 'TRD36', 'TRD37', 'TRD38', 'TRD39', 'TRD40', 'TRD41', 'TRD42', 'TRD43', 'TRD21', 'TRD44', 'TRD45', 'TRD46', 'TRD47', 'TRD48', 'TRD49', 'TRD50', 'TRD51', 'TRD52', 'TRD53', 'TRD54', 'TRD55', 'TRD56']
data.fillna(0, inplace=True)
del data['ID']
del data['ID_litter']
del data['group']
del data['IgGJ2']
del data['AgeD2']
del data['Age_D1']
del data['Min1inflcr']
del data['Size']
del data['sex']
data.head()

,litt_size,TPI,Died,hospit,InfCroissPed,InfCroiss4,InfCroiss5,InfCroiss6,InfCroiss7,InfCroiss8,...,TRD48,TRD49,TRD50,TRD51,TRD52,TRD53,TRD54,TRD55,TRD56,Diarr
0,5,0.0,1,1,1,1,0,0,0.0,0.0,...,38.4,38.2,38.4,38.9,38.7,38.5,38.7,39.0,39.0,1
1,5,0.0,0,0,1,1,0,0,0.0,0.0,...,38.4,37.4,37.8,39.1,38.1,38.7,37.7,37.9,38.3,1
2,5,0.0,0,0,1,0,1,0,0.0,0.0,...,38.2,38.4,38.1,38.8,39.1,37.4,38.0,38.2,37.6,0
3,5,0.0,0,1,1,0,1,0,0.0,0.0,...,38.4,38.4,38.4,38.9,38.3,38.5,38.6,38.0,38.0,1
4,5,0.0,0,1,1,0,1,0,0.0,1.0,...,38.3,38.7,38.6,39.1,37.4,37.4,37.4,37.4,37.4,1

In [99]:
from sklearn.linear_model import Ridge
X=data.drop(["Diarr"], axis = 1)
Y=data['Diarr']
ridge = Ridge(alpha=1.0)
ridge.fit(X,Y)

Ridge()

In [100]:
ridge=Ridge(alpha=1.0)
ridge.fit(X,Y)
predictors=X.columns
coef=pd.Series(ridge.coef_,predictors).sort_values(ascending=False)
print(coef)

hospit          0.714695
Died            0.224922
TRD39           0.162603
TRD44           0.156917
TRD53           0.149231
TRD48           0.122986
InfCroiss8      0.121642
InfCroiss5      0.118985
InfCroiss4      0.095640
TRD26           0.082417
TRD49           0.074685
TRD43           0.067677
TRD55           0.063568
InfCroissPed    0.059824
InfCroiss6      0.036969
TRD28           0.033200
TRD47           0.031558
InfCroiss7      0.025466
TRD52           0.021108
TRD25           0.011549
TRD42           0.006643
TPI             0.006472
litt_size       0.004875
TRD46          -0.000287
TRD56          -0.000645
TRD32          -0.008516
TRD23          -0.010095
TRD33          -0.013602
TRD41          -0.025617
TRD51          -0.027315
TRD27          -0.030252
TRD36          -0.037885
TRD37          -0.038254
TRD22          -0.049926
TRD40          -0.057092
TRD38          -0.064010
TRD24          -0.081814
TRD35          -0.088722
TRD34          -0.092070
TRD29          -0.095316
TRD31          -0.105130
TRD21          -0.115555
TRD30          -0.133199
TRD50          -0.139489
TRD45          -0.139522
TRD54          -0.189475
dtype: float64

#### Lasso

In [101]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=1)
lasso.fit(X,Y)
predictors=X.columns
coef=pd.Series(lasso.coef_,predictors).sort_values()
print(coef)

litt_size       0.0
TRD36          -0.0
TRD37           0.0
TRD38           0.0
TRD39           0.0
TRD40           0.0
TRD41          -0.0
TRD42           0.0
TRD43           0.0
TRD44           0.0
TRD45           0.0
TRD46           0.0
TRD47           0.0
TRD48           0.0
TRD49           0.0
TRD50          -0.0
TRD51           0.0
TRD52           0.0
TRD53           0.0
TRD54           0.0
TRD35           0.0
TRD34           0.0
TRD33           0.0
TRD32           0.0
TPI            -0.0
Died            0.0
hospit          0.0
InfCroissPed    0.0
InfCroiss4      0.0
InfCroiss5      0.0
InfCroiss6      0.0
InfCroiss7      0.0
InfCroiss8      0.0
TRD55           0.0
TRD21          -0.0
TRD23          -0.0
TRD24          -0.0
TRD25          -0.0
TRD26           0.0
TRD27           0.0
TRD28           0.0
TRD29          -0.0
TRD30           0.0
TRD31           0.0
TRD22           0.0
TRD56           0.0
dtype: float64

### Cible 'hospit'

In [93]:
data = pd.read_csv("DataH.csv")
names=['litt_size','TPI','Died','Diarr','InfCroissPed', 'InfCroiss4', 'InfCroiss5', 'InfCroiss6', 'InfCroiss7', 'InfCroiss8', 'TRD21', 'TRD22', 'TRD23', 'TRD24', 'TRD25', 'TRD26', 'TRD27', 'TRD28', 'TRD29', 'TRD30', 'TRD31', 'TRD32', 'TRD33', 'TRD34', 'TRD35', 'TRD36', 'TRD37', 'TRD38', 'TRD39', 'TRD40', 'TRD41', 'TRD42', 'TRD43', 'TRD21', 'TRD44', 'TRD45', 'TRD46', 'TRD47', 'TRD48', 'TRD49', 'TRD50', 'TRD51', 'TRD52', 'TRD53', 'TRD54', 'TRD55', 'TRD56']
data.fillna(0, inplace=True)
del data['ID']
del data['ID_litter']
del data['group']
del data['IgGJ2']
del data['AgeD2']
del data['Age_D1']
del data['Min1inflcr']
del data['Size']
del data['sex']
data.head()

,litt_size,TPI,Died,Diarr,InfCroissPed,InfCroiss4,InfCroiss5,InfCroiss6,InfCroiss7,InfCroiss8,...,TRD48,TRD49,TRD50,TRD51,TRD52,TRD53,TRD54,TRD55,TRD56,hospit
0,5,0.0,1,1,1,1,0,0,0.0,0.0,...,38.4,38.2,38.4,38.9,38.7,38.5,38.7,39.0,39.0,1
1,5,0.0,0,1,1,1,0,0,0.0,0.0,...,38.4,37.4,37.8,39.1,38.1,38.7,37.7,37.9,38.3,0
2,5,0.0,0,0,1,0,1,0,0.0,0.0,...,38.2,38.4,38.1,38.8,39.1,37.4,38.0,38.2,37.6,0
3,5,0.0,0,1,1,0,1,0,0.0,0.0,...,38.4,38.4,38.4,38.9,38.3,38.5,38.6,38.0,38.0,1
4,5,0.0,0,1,1,0,1,0,0.0,1.0,...,38.3,38.7,38.6,39.1,37.4,37.4,37.4,37.4,37.4,1

In [94]:
from sklearn.linear_model import Ridge
X=data.drop(["hospit"], axis = 1)
Y=data['hospit']
ridge = Ridge(alpha=1.0)
ridge.fit(X,Y)

Ridge()

In [95]:
ridge=Ridge(alpha=1.0)
ridge.fit(X,Y)
predictors=X.columns
coef=pd.Series(ridge.coef_,predictors).sort_values(ascending=False)
print(coef)

Diarr           0.484349
TRD38           0.214908
TRD24           0.210057
TRD31           0.175193
Died            0.172844
TRD32           0.135998
TRD34           0.114144
TRD21           0.108962
TRD51           0.103572
TRD46           0.093837
InfCroiss6      0.088684
TPI             0.083372
TRD22           0.077783
TRD28           0.070470
InfCroissPed    0.053623
InfCroiss8      0.036934
TRD29           0.035150
TRD26           0.033633
TRD35           0.031043
TRD36           0.030887
InfCroiss7      0.022424
TRD45           0.021442
TRD54           0.021078
TRD33           0.020846
TRD47           0.017019
TRD49           0.015658
TRD42           0.013583
TRD40           0.012219
litt_size       0.011833
TRD30           0.008184
TRD27           0.002467
TRD55          -0.005661
TRD52          -0.008135
TRD39          -0.025148
TRD53          -0.026738
TRD56          -0.036804
TRD37          -0.038314
TRD41          -0.064799
TRD43          -0.064812
TRD50          -0.068031
TRD48          -0.072828
InfCroiss5     -0.078674
TRD23          -0.087423
InfCroiss4     -0.095878
TRD44          -0.157800
TRD25          -0.200830
dtype: float64

#### Lasso

In [96]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=1)
lasso.fit(X,Y)
predictors=X.columns
coef=pd.Series(lasso.coef_,predictors).sort_values()
print(coef)

litt_size       0.0
TRD36           0.0
TRD37           0.0
TRD38           0.0
TRD39           0.0
TRD40           0.0
TRD41          -0.0
TRD42           0.0
TRD43           0.0
TRD44           0.0
TRD45           0.0
TRD46           0.0
TRD47           0.0
TRD48          -0.0
TRD49           0.0
TRD50          -0.0
TRD51           0.0
TRD52          -0.0
TRD53           0.0
TRD54           0.0
TRD35           0.0
TRD34           0.0
TRD33           0.0
TRD32           0.0
TPI             0.0
Died            0.0
Diarr           0.0
InfCroissPed    0.0
InfCroiss4     -0.0
InfCroiss5      0.0
InfCroiss6      0.0
InfCroiss7      0.0
InfCroiss8      0.0
TRD55          -0.0
TRD21           0.0
TRD23           0.0
TRD24           0.0
TRD25          -0.0
TRD26           0.0
TRD27           0.0
TRD28           0.0
TRD29           0.0
TRD30           0.0
TRD31           0.0
TRD22           0.0
TRD56          -0.0
dtype: float64